# Dependencies
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
 extensions: [fenced_code_blocks]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mathematics and Statistics Seminars
tagline:             'Northern Arizona University'
description:         'NAU Math & Stats Seminars'
url:                 'http://NAUMathStat.github.io'
baseurl:             '/seminars'
paginate:            10

# About/contact
author:
  name:              Cool people
  url:               https://twitter.com/danaernst
  email:             dana@danaernst.com

# Custom vars
version:             1.0.0

# GitHub
github:
  repo:             github.com/NAUMathStat/seminars

# This is the list of pages to incldue in archive
# pages_list:       {'About':'about','Colloquium':'colloquium','Applied Math Seminar':'ams','ACGT Seminar':'acgt','Teaching Showcase':'teaching','FAMUS':'famus'}
#,'Archive':'archive','Feed':'atom.xml'}
