# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               NAU Mathematics and Statistics Seminars
tagline:             'Some wicked awesome stuff!'
description:         'Something clever here.'
url:                 'http://NAUMathStat.github.io'
baseurl:             '/seminars/'
paginate:            10

# About/contact
author:
  name:              Cool people
  url:               https://twitter.com/danaernst
  email:             dana@danaernst.com

# Custom vars
version:             1.0.0

# GitHub
github:
  repo:             github.com/NAUMathStat/seminars

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'about','Archive':'/archive','Feed':'/atom.xml'}
